-- ZenCap Production Database
-- Seed Data: Financial Models Catalog

BEGIN;

INSERT INTO models (slug, title, description, category, thumbnail_url, file_url, price, status, tags, excel_url) VALUES

-- Private Equity Real Estate Models
('multifamily-real-estate-model',
'Multifamily Real Estate Investment Model',
'Comprehensive financial model for multifamily real estate investments, featuring detailed cash flow projections, sensitivity analysis, and return calculations for apartment complexes and residential properties.',
'private-equity',
'/images/models/multifamily-thumbnail.jpg',
'/models/multifamily-real-estate-model.xlsx',
4985.00,
'active',
'real estate, multifamily, private equity, cash flow',
'/models/multifamily-real-estate-model.xlsx'),

('mixed-use-development-model',
'Mixed-Use Development Financial Model',
'Advanced financial modeling tool for mixed-use development projects, incorporating residential, commercial, and retail components with detailed construction and leasing assumptions.',
'private-equity',
'/images/models/mixed-use-thumbnail.jpg',
'/models/mixed-use-development-model.xlsx',
4985.00,
'active',
'real estate, mixed-use, development, private equity',
'/models/mixed-use-development-model.xlsx'),

('commercial-real-estate-model',
'Commercial Real Estate Investment Model',
'Professional-grade model for commercial real estate investments, including office buildings, retail centers, and industrial properties with comprehensive valuation methods.',
'private-equity',
'/images/models/commercial-thumbnail.jpg',
'/models/commercial-real-estate-model.xlsx',
4985.00,
'active',
'real estate, commercial, office, retail, industrial',
'/models/commercial-real-estate-model.xlsx'),

('hospitality-real-estate-model',
'Hospitality Real Estate Investment Model',
'Specialized financial model for hotel and hospitality real estate investments, featuring RevPAR analysis, seasonal adjustments, and management fee structures.',
'private-equity',
'/images/models/hospitality-thumbnail.jpg',
'/models/hospitality-real-estate-model.xlsx',
4985.00,
'active',
'real estate, hospitality, hotels, private equity',
'/models/hospitality-real-estate-model.xlsx'),

-- Public Equity Models
('nvidia-financial-model',
'NVIDIA Corporation Financial Model',
'Comprehensive financial model for NVIDIA Corporation, incorporating semiconductor cycles, AI market growth, data center revenue, and gaming segment analysis.',
'public-equity',
'/images/models/nvidia-thumbnail.jpg',
'/models/nvidia-financial-model.xlsx',
2985.00,
'active',
'NVIDIA, semiconductors, AI, technology, public equity',
'/models/nvidia-financial-model.xlsx'),

('apple-financial-model',
'Apple Inc. Financial Model',
'Detailed financial model for Apple Inc., featuring product segment analysis, services growth, international markets, and comprehensive valuation methodologies.',
'public-equity',
'/images/models/apple-thumbnail.jpg',
'/models/apple-financial-model.xlsx',
2985.00,
'active',
'Apple, technology, consumer electronics, public equity',
'/models/apple-financial-model.xlsx'),

('microsoft-financial-model',
'Microsoft Corporation Financial Model',
'Advanced model for Microsoft Corporation, analyzing cloud computing growth, productivity software, gaming, and enterprise solutions with detailed scenario analysis.',
'public-equity',
'/images/models/microsoft-thumbnail.jpg',
'/models/microsoft-financial-model.xlsx',
2985.00,
'active',
'Microsoft, cloud computing, enterprise software, public equity',
'/models/microsoft-financial-model.xlsx'),

('tesla-financial-model',
'Tesla Inc. Financial Model',
'Comprehensive Tesla financial model incorporating automotive sales, energy storage, solar, and autonomous driving technology with production scaling analysis.',
'public-equity',
'/images/models/tesla-thumbnail.jpg',
'/models/tesla-financial-model.xlsx',
2985.00,
'active',
'Tesla, electric vehicles, energy storage, technology',
'/models/tesla-financial-model.xlsx'),

('amazon-financial-model',
'Amazon.com Inc. Financial Model',
'Detailed Amazon financial model covering e-commerce, AWS cloud services, advertising, and logistics with comprehensive segment analysis and projections.',
'public-equity',
'/images/models/amazon-thumbnail.jpg',
'/models/amazon-financial-model.xlsx',
2985.00,
'active',
'Amazon, e-commerce, cloud computing, AWS, public equity',
'/models/amazon-financial-model.xlsx'),

-- Financial Planning and Valuation Tools
('dcf-valuation-model',
'Discounted Cash Flow (DCF) Valuation Model',
'Professional DCF valuation model with advanced features including terminal value calculations, sensitivity analysis, and scenario planning for comprehensive equity valuation.',
'valuation',
'/images/models/dcf-thumbnail.jpg',
'/models/dcf-valuation-model.xlsx',
1985.00,
'active',
'DCF, valuation, discounted cash flow, equity analysis',
'/models/dcf-valuation-model.xlsx'),

('lbo-financial-model',
'Leveraged Buyout (LBO) Financial Model',
'Comprehensive LBO model featuring debt structuring, equity returns analysis, and transaction modeling for private equity leveraged buyout transactions.',
'private-equity',
'/images/models/lbo-thumbnail.jpg',
'/models/lbo-financial-model.xlsx',
4985.00,
'active',
'LBO, leveraged buyout, private equity, debt financing',
'/models/lbo-financial-model.xlsx'),

('merger-acquisition-model',
'Merger & Acquisition Financial Model',
'Advanced M&A model with accretion/dilution analysis, synergies modeling, and transaction structure optimization for strategic and financial buyers.',
'valuation',
'/images/models/ma-thumbnail.jpg',
'/models/merger-acquisition-model.xlsx',
3485.00,
'active',
'M&A, mergers, acquisitions, synergies, valuation',
'/models/merger-acquisition-model.xlsx');

COMMIT;